Manually install git-extra
This would fail in the `sync` job
(https://github.com/git-for-windows/git-sdk-arm64/actions/runs/3967702749/jobs/6799975467#step:4:105):

	[...]
	Packages (1) git-extra-1.1.622.c80936e11-1
	warning: no /var/cache/pacman/pkg/ cache exists, creating...

	Total Download Size:   0.12 MiB
	Total Installed Size:  0.48 MiB
	Net Upgrade Size:      0.00 MiB

	:: Proceed with installation? [Y/n]
	:: Retrieving packages...
	 git-extra-1.1.622.c80936e11-1-x86_64 downloading...
	checking keyring...
	checking package integrity...
	loading package files...
	checking for file conflicts...
	checking available disk space...
	:: Processing package changes...
	upgrading git-extra...
	No second pass needed
	warning: database file for 'git-for-windows-aarch64' does not exist (use '-Sy' to download)
	warning: git-extra-1.1.622.c80936e11-1 is up to date -- reinstalling
	error: failed to prepare transaction (could not find database)

	Error: Process completed with exit code 1.

The reason is that the database `git-for-windows-aarch64` is added to
`/etc/pacman.conf` as part of `git-extra`'s post-install script, and the
`sync` job omits updating the databases after the initial update (i.e.
after the first pass of installing any packages), intentionally.

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>